// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
//    protoc-gen-grpc-gateway-gosdk 1.8.1-next-f3e4de
// type: fake_userv1_client

package fake

import (
	"github.com/jaronnie/autosdk/rest"
	"github.com/jaronnie/autosdk/typed/userv1"
)

type FakeUserv1 struct{}

func (f *FakeUserv1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (f *FakeUserv1) User() userv1.UserInterface {
	return &FakeUser{Fake: f}
}
