// Code generated by protoc-gen-grpc-gateway-go. DO NOT EDIT.
//    protoc-gen-grpc-gateway-go 1.7.1-next-bbbf72
// type: fake_corev1_client

package fake

import (
	"github.com/jaronnie/autosdk/rest"
	"github.com/jaronnie/autosdk/typed/corev1"
)

type FakeCorev1 struct{}

func (f *FakeCorev1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (f *FakeCorev1) Credential() corev1.CredentialInterface {
	return &FakeCredential{Fake: f}
}

func (f *FakeCorev1) Machine() corev1.MachineInterface {
	return &FakeMachine{Fake: f}
}
