// Code generated by protoc-gen-grpc-gateway-go. DO NOT EDIT.
// versions:
//    protoc-gen-grpc-gateway-go 1.7.1-next-bbbf72
// type: fake_machine

package fake

import (
	"context"

	"github.com/jaronnie/autosdk/pb/corev1"
	"github.com/jaronnie/autosdk/rest"
)

var (
	FakeReturnInitMachine     = &corev1.Machine{}
	FakeReturnDownloadMachine = &rest.Request{}
)

type MachineGetter interface {
	Machine() MachineInterface

	FakeMachineExpansion
}

type MachineInterface interface {
	InitMachine(ctx context.Context, param *corev1.Machine) (*corev1.Machine, error)
	DownloadMachine(param *corev1.Machine) (*rest.Request, error)
}

type FakeMachine struct {
	Fake *FakeCorev1
}

func (f *FakeMachine) InitMachine(ctx context.Context, param *corev1.Machine) (*corev1.Machine, error) {
	return FakeReturnInitMachine, nil
}

func (f *FakeMachine) DownloadMachine(param *corev1.Machine) (*rest.Request, error) {
	return FakeReturnDownloadMachine, nil
}
