// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"context"

	"github.com/jaronnie/autosdk/pb/corev1"
)

var (
	FakeReturnInitMachine = &corev1.Machine{}
)

type MachineGetter interface {
	Machine() MachineInterface
}

type MachineInterface interface {
	InitMachine(ctx context.Context, param *corev1.Machine) (*corev1.Machine, error)
}

type FakeMachine struct {
	Fake *FakeCorev1
}

func (x *FakeMachine) InitMachine(ctx context.Context, param *corev1.Machine) (*corev1.Machine, error) {
	return FakeReturnInitMachine, nil
}
