// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
// versions:
//    protoc-gen-go-httpsdk 1.7.1-next-bad862
// type: fake_direct_client

package fake

import (
	"github.com/jaronnie/autosdk/rest"
)

type FakeDirect struct{}

func (f *FakeDirect) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
