.PHONY: gensdk
gensdk:
	@export PATH=`pwd`/tools/proto/bin:"${PATH}" && sh script/generate.sh

.PHONY: gensdk.debug
gensdk.debug:
	@export PATH=`pwd`/tools/proto/bin:"${PATH}" && sh script/generate.sh debug
