// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
// versions:
//    protoc-gen-grpc-gateway-gosdk 1.8.1-next-f3e4de
// type: bv1_client

package bv1

import (
	"github.com/jaronnie/autosdk/rest"
)

type Bv1Interface interface {
	RESTClient() rest.Interface

	UserGetter
}

type Bv1Client struct {
	restClient rest.Interface
}

func (x *Bv1Client) RESTClient() rest.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *Bv1Client) User() UserInterface {
	return newUserClient(x)
}

// NewForConfig creates a new Bv1Client for the given config.
func NewForConfig(x *rest.RESTClient) (*Bv1Client, error) {
	config := *x
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &Bv1Client{client}, nil
}
