// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
// versions:
//    protoc-gen-grpc-gateway-gosdk 1.8.1-next-f3e4de
// type: av1_client

package av1

import (
	"github.com/jaronnie/autosdk/rest"
)

type Av1Interface interface {
	RESTClient() rest.Interface

	UserGetter
}

type Av1Client struct {
	restClient rest.Interface
}

func (x *Av1Client) RESTClient() rest.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *Av1Client) User() UserInterface {
	return newUserClient(x)
}

// NewForConfig creates a new Av1Client for the given config.
func NewForConfig(x *rest.RESTClient) (*Av1Client, error) {
	config := *x
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &Av1Client{client}, nil
}
