// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
// versions:
//    protoc-gen-grpc-gateway-gosdk 1.8.1-next-f3e4de
// type: user

package av1

import (
	"context"

	"github.com/jaronnie/autosdk/pb/apb"
	"github.com/jaronnie/autosdk/rest"
)

type UserGetter interface {
	User() UserInterface
}

type UserInterface interface {
	// Add trans *apb.AddUserReq into *apb.AddUserResp
	// API /gateway/a/api/v1.0/user/add
	Add(ctx context.Context, param *apb.AddUserReq) (*apb.AddUserResp, error)

	UserExpansion
}

type userClient struct {
	client rest.Interface
}

func newUserClient(c *Av1Client) *userClient {
	return &userClient{
		client: c.RESTClient(),
	}
}

func (x *userClient) Add(ctx context.Context, param *apb.AddUserReq) (*apb.AddUserResp, error) {
	var resp apb.AddUserResp
	err := x.client.Verb("GET").
		SubPath(
			"/gateway/a/api/v1.0/user/add",
		).
		Params(
			rest.QueryParam{Name: "name", Value: param.Name},
			rest.QueryParam{Name: "age", Value: param.Age},
		).
		Body(nil).
		Do(ctx).
		Into(&resp, false)

	if err != nil {
		return nil, err
	}

	return &resp, nil
}
