// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
// versions:
//    protoc-gen-grpc-gateway-gosdk 1.7.1-next-6ba19e
// type: fake_clientset

package fake

import (
	"github.com/jaronnie/protoc-gen-grpc-gateway-gosdk/grpc-restful/pkgsdk/typed"
	"github.com/jaronnie/protoc-gen-grpc-gateway-gosdk/grpc-restful/pkgsdk/typed/fake"
	userv1 "github.com/jaronnie/protoc-gen-grpc-gateway-gosdk/grpc-restful/pkgsdk/typed/userv1"
	fakeuserv1 "github.com/jaronnie/protoc-gen-grpc-gateway-gosdk/grpc-restful/pkgsdk/typed/userv1/fake"
)

type Clientset struct{}

func (f *Clientset) Direct() typed.DirectInterface {
	return &fake.FakeDirect{}
}

func (f *Clientset) Userv1() userv1.Userv1Interface {
	return &fakeuserv1.FakeUserv1{}
}
