// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
// versions:
//    protoc-gen-grpc-gateway-gosdk 1.7.1-next-6ba19e
// type: fake_direct_client

package fake

import (
	"github.com/jaronnie/autosdk/rest"
)

type FakeDirect struct{}

func (f *FakeDirect) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
