// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
//    protoc-gen-grpc-gateway-gosdk 1.7.1-next-6ba19e
// type: fake_userv1_client

package fake

import (
	"github.com/jaronnie/protoc-gen-grpc-gateway-gosdk/grpc-restful/pkgsdk/rest"
	"github.com/jaronnie/protoc-gen-grpc-gateway-gosdk/grpc-restful/pkgsdk/typed/userv1"
)

type FakeUserv1 struct{}

func (f *FakeUserv1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (f *FakeUserv1) User() userv1.UserInterface {
	return &FakeUser{Fake: f}
}
