package fake

type ClientSetData struct {
	GoModule      string            // github.com/jaronnie/autosdk
	ScopeVersions map[string]string // ["corev1":"CoreV1", "oauthv1":"OauthV1"]
}

var FakeClientSetTpl = `
// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
// versions:
//    protoc-gen-grpc-gateway-gosdk {{getProtoToolsVersion "protoc-gen-grpc-gateway-gosdk"}}
// type: fake_clientset

package fake

import (
	"{{.GoModule}}/typed"
	"{{.GoModule}}/typed/fake"

	{{range $k, $v := .ScopeVersions}}{{$k}} "{{$.GoModule}}/typed/{{$k}}"
	fake{{$k}} "{{$.GoModule}}/typed/{{$k}}/fake"
	{{end}}
)

type Clientset struct {}

func (f *Clientset) Direct() typed.DirectInterface {
	return &fake.FakeDirect{}
}

{{range $k, $v := .ScopeVersions}}func (f *Clientset) {{$v}}() {{$k}}.{{$v}}Interface {
	return &fake{{$k}}.Fake{{$v}}{}
}

{{end}}
`
