// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package corev1

import (
	"github.com/jaronnie/autosdk/pb/corev1"
	"github.com/jaronnie/autosdk/rest"
)

type MachineGetter interface {
	Machine() MachineInterface
}

type MachineInterface interface {
	// InitMachine Implement: /gateway/core/api/v1/machine/init
	// Trans *corev1.Machine into *corev1.Machine
	InitMachine(param *corev1.Machine) (*rest.Request, error)

	// DownloadMachine Implement: /gateway/core/api/v1/machine/download
	// Trans *corev1.Machine into *corev1.Machine
	// stream
	DownloadMachine(param *corev1.Machine) (*rest.Request, error)

	MachineExpansion
}

type machineClient struct {
	client rest.Interface
}

func newMachineClient(c *Corev1Client) *machineClient {
	return &machineClient{
		client: c.RESTClient(),
	}
}

func (x *machineClient) InitMachine(param *corev1.Machine) (*rest.Request, error) {
	request := x.client.Verb("POST").
		SubPath(
			"/gateway/core/api/v1/machine/init",
		).
		Params().
		Body(param)

	return request, nil
}

func (x *machineClient) DownloadMachine(param *corev1.Machine) (*rest.Request, error) {
	request := x.client.Verb("POST").
		SubPath(
			"/gateway/core/api/v1/machine/download",
		).
		Params().
		Body(param)

	return request, nil
}
