// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package corev1

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"

	"github.com/jaronnie/autosdk/pb/corev1"
	"github.com/jaronnie/autosdk/rest"
)

type MachineGetter interface {
	Machine() MachineInterface
}

type MachineInterface interface {
	InitMachine(ctx context.Context, param *corev1.Machine) (*corev1.Machine, error)
}

type machineClient struct {
	client rest.Interface
}

func newMachineClient(c *Corev1Client) *machineClient {
	return &machineClient{
		client: c.RESTClient(),
	}
}

func (x *machineClient) InitMachine(ctx context.Context, param *corev1.Machine) (*corev1.Machine, error) {
	var resp corev1.Machine
	response, err := x.client.Verb("POST").
		SubPath(
			"/api/v1/machine/init",
		).
		Params().
		Body(param).
		Do(ctx).
		RawResponse()

	if err != nil {
		return nil, err
	}

	jsonb := new(runtime.JSONPb)
	err = jsonb.Unmarshal(response, &resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
