// Code generated by protoc-gen-grpc-gateway-go. DO NOT EDIT.
// versions:
//    protoc-gen-grpc-gateway-go 1.7.1-next-bbbf72
// type: direct_client

package typed

import (
	"github.com/jaronnie/autosdk/rest"
)

type DirectInterface interface {
	RESTClient() rest.Interface
}

type DirectClient struct {
	restClient rest.Interface
}

func (x *DirectClient) RESTClient() rest.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

// NewForConfig creates a new DirectClient for the given config.
func NewForConfig(x *rest.RESTClient) (*DirectClient, error) {
	config := *x
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &DirectClient{client}, nil
}
