// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
//    protoc-gen-grpc-gateway-gosdk 1.8.1-next-f3e4de
// type: fake_av1_client

package fake

import (
	"github.com/jaronnie/autosdk/rest"
	"github.com/jaronnie/autosdk/typed/av1"
)

type FakeAv1 struct{}

func (f *FakeAv1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (f *FakeAv1) User() av1.UserInterface {
	return &FakeUser{Fake: f}
}
