// Code generated by protoc-gen-grpc-gateway-gosdk. DO NOT EDIT.
// versions:
//    protoc-gen-grpc-gateway-gosdk 1.8.1-next-f3e4de
// type: fake_user

package fake

import (
	"context"

	"github.com/jaronnie/autosdk/pb/bpb"
)

var (
	FakeReturnAdd = &bpb.AddUserResp{}
)

type UserGetter interface {
	User() UserInterface

	FakeUserExpansion
}

type UserInterface interface {
	Add(ctx context.Context, param *bpb.AddUserReq) (*bpb.AddUserResp, error)
}

type FakeUser struct {
	Fake *FakeBv1
}

func (f *FakeUser) Add(ctx context.Context, param *bpb.AddUserReq) (*bpb.AddUserResp, error) {
	return FakeReturnAdd, nil
}
