// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/jaronnie/protoc-gen-grpc-gateway-gosdk/grpc-restful/internal/logic"
	"github.com/jaronnie/protoc-gen-grpc-gateway-gosdk/grpc-restful/internal/svc"
	"github.com/jaronnie/protoc-gen-grpc-gateway-gosdk/grpc-restful/userpb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Add(ctx context.Context, in *userpb.AddUserReq) (*userpb.AddUserResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
